name: Test tutorial

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: test
        python-version: "3.9"

    - name: run tutorial
      run: |
        mkdir tutorial
        source fetch_tutorial_files.sh tutorial/

        cd tutorial
        source ../install_module0_flow-login_node.sh test

        cd module0_flow
        source ../../run_module0_flow_example.sh h5flow_data/larndsim.example.h5
